### ISSUE TITLE
UX - Přehled uživatelů ve skupině/konverzaci

### ISSUE THREAD

**Issue by LukasVaculcik** [brezinajn/Stalker#14]
Uvítal bych možnost vidět seznam lidí kdo je v dané skupině nebo konverzaci.

**Comment by brezinajn** [comment]
Jojo bude potreba pridat celou aktivitu pro detail a osobni nastavni memer grupy

**Comment by brezinajn** [comment]
Implemented in [c0c0642](https://github.com/brezinajn/Stalker/commit/c0c064205c84ba36b1d49a6198a502cc583e349c).
