### ISSUE TITLE
Logon se nedokonci

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#16]
Po zadani spravneho user_logonu a hesla se pozadi zmeni na lognutou aplikaci, ale v popredi je stale tocici se kolecko. Po stisknuti zpet kolecko zmizi a je mozne aplikaci pouzivat.

**Comment by Downwall** [comment]
Provedl jsem logoff, ukoncil aplikaci, otevrel znovu a uz se to povedlo hned.

**Comment by brezinajn** [comment]
Tohle se poresi az pridam dialogy na login error. Ted neni videt co se deje.
