### ISSUE TITLE
Pouziti sipky je matouci

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#17]
Sipka vlevo nahore vraci z jakekoliv hloubky a sekce vzdy na news.

**Comment by brezinajn** [comment]
Sipka vraci na parent aktivitu. To je v poradku. Problem je ze main aktivita si vzdycky nahodi news. Vim o tom. Dekuji

**Comment by brezinajn** [comment]
Viz banking > new transfer. tam zkus sipku z5

**Comment by brezinajn** [comment]
Fixed [here](https://github.com/brezinajn/Stalker/commit/1435285ca5d5380bc3e9bf253342011e7442560f).
