### ISSUE TITLE
Automaticke nescrollovani

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#18]
Po odeslani zpravy zustane stranka, kde je. Preferoval bych automaticke scrollovani na nejnovejsi zpravu ve skupine.

**Comment by brezinajn** [comment]
Jo je to v planu. Jak po otevreni aktivity s konverzaci tak po prijmuti message. Problem je, ze netusim jak se to dela :D

**Comment by brezinajn** [comment]
Fixed by [9a49917](https://github.com/brezinajn/Stalker/commit/b1da70164840f7043dea53a71e11a29a282a13c7).
