### ISSUE TITLE
Neukladani user_logonu

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#19]
Neni mozne si ulozit user_logon. Nez to tam vsechno natukam, tak mi Stalker utece pred ocima :D

**Comment by brezinajn** [comment]
Odhlasuje se ti appka sama?

**Comment by brezinajn** [comment]
Viz. [tenhle ticket](https://github.com/brezinajn/Stalker/issues/4).

**Comment by Downwall** [comment]
Jj, duplicita
