### ISSUE TITLE
Neni informace o nove skupine

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#20]
Chybi mi info o tom, ze jsem byl a kym pridan do jake skupiny ...

**Comment by LukasVaculcik** [comment]
Tohle by se mohlo logicky vyresit ze poslu pozvanku a musi ji druha strana prijmout. Jinak muzu porad pridavat lidi do svych konverzaci a spamovat je.

**Comment by brezinajn** [comment]
To co pise Elvis je ideal jak bych to chtel vyresit. V praxi to asi vyresim tak, ze pozvaej bude do skupiny automaticky pridanej, pridanyho to informuje notifikaci, ale nezapnou se mu notifikace na message, aby se nedalo spammit. Resp kdyz budes spammit bude to k hovnu.

**Comment by brezinajn** [comment]
Jinak k tomu co psal Downie. Notifikace budou.

**Comment by brezinajn** [comment]
Duplicita s #25
