### ISSUE TITLE
Zaseknuti se v settings

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#21]
Po provedeni nastaveni na tabletu v sekci settings jsem chtel odejit zpet a az na cca desaty pokus mackani zpet a sipky me to pustilo na news.

**Comment by brezinajn** [comment]
Dej mi pls model number tabletu.

**Comment by Downwall** [comment]
Cube U65GT

**Comment by brezinajn** [comment]
Nedari se mi replikovat.
