### ISSUE TITLE
Vlastni jmeno pri zalozeni skupiny

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#22]
Formular nabizi pri zakladani skupiny jmeno prihlaseneho uzivatele (budouciho ownera). Neni to dulezite a jen zabira misto.

**Comment by brezinajn** [comment]
Jako ze ti naseptava jeho mail?

**Comment by Downwall** [comment]
Nn, ale muzu se pridat jako clen skupiny. Kdyz uz ji vlastnim, tak mi to prijde zbytecne ...

**Comment by brezinajn** [comment]
jo, nemůžeš 😀 jen jsi ve výběru. j vím o tom a nepůjde to vyřešit dokud se
nezbavim firebaseui na manage listů
