### ISSUE TITLE
Grupy se radi na UKacko ...

### ISSUE THREAD

**Issue by Downwall** [brezinajn/Stalker#23]
Radit grupy rozumne (podle jmena)

**Comment by brezinajn** [comment]
Grupy se radi abecedne :), jen a < Z

**Comment by Downwall** [comment]
Mohlo by to razeni byt caseinsensitive?

**Comment by brezinajn** [comment]
Dokud nenapisu vlastni alternativu k firebaseUI ktery se pouziva na login a zobrazovani vsech listu, tak bohuzel ne.

**Comment by brezinajn** [comment]
Resp. asi bych mohl do db pridat caseinsensitive field podle kteryho se to bude radit

**Comment by brezinajn** [comment]
Denormalizovanej model nepujde radit
