### ISSUE TITLE
UX - Login remember

### ISSUE THREAD

**Issue by LukasVaculcik** [brezinajn/Stalker#4]
Možnost zapamatovat si login údaje, pokuď to nepamatování není security feature :-)

**Comment by brezinajn** [comment]
Odlogovava se ti to samo?

**Comment by LukasVaculcik** [comment]
To ne.

**Comment by brezinajn** [comment]
v tom případě to asi není nutný, ale mělo by to umět naseptavat maily z
contactu

**Comment by brezinajn** [comment]
Solved in firebaseUI 0.4.0
